jwt:
  signing_secret: fjd3252jrkal;f234fk
  admin:
    signing_secret: 32fj32l3;f032f09f32

server:
  port: "8080"

db:
  url: localhost
  port: "3306"
  username: root
  password: secret
  db_name: api_proxy